require('dotenv').config()
const express = require('express')
const cors = require('cors')
const fileUpload =  require('express-fileupload')
const cookieParser = require('cookie-parser')
const session = require('express-session')
const MongoStore = require('connect-mongo');

const userRoutes = require('./routes/user.routes');
const productRoutes = require('./routes/product.routes');
const cartRoutes = require('./routes/cart.routes');
const offerRoutes = require('./routes/offers.routes');
const verifRoutes = require('./routes/verif.routes');
const contactRoutes = require('./routes/contact.routes');

const app = express()
app.use(express.json())
app.use(cookieParser())
app.use(session({
  secret: 'random key generated by monkeys', 
  resave: false, 
  saveUninitialized: false,
  store: MongoStore.create({
    mongoUrl: process.env.MONGODB_URL
  }),
  cookie: { maxAge: 60 * 60 * 24 } //dure une journée
}))
app.use(cors())
app.use(fileUpload({
  useTempFiles: true
}))
app.use(function(req,res,next) {
  res.locals.session = req.session;
  next();
})

// routes

app.use('/api/user', userRoutes);
app.use('/api/products', productRoutes);
app.use('/api/offers', offerRoutes);
app.use('/api/verif', verifRoutes);
app.use('/api/contact', contactRoutes);
app.use('/api/cart', cartRoutes);

module.exports = app