require('dotenv').config()
const express = require('express')
const mongoose = require('mongoose')
const cors = require('cors')
const fileUpload =  require('express-fileupload')
const cookieParser = require('cookie-parser')
const session = require('express-session')
const MongoStore = require('connect-mongo');

const userRoutes = require('./routes/user.routes');
const productRoutes = require('./routes/product.routes');
const cartRoutes = require('./routes/cart.routes');
const verifRoutes = require('./routes/verif.routes');

const app = express()
app.use(express.json())
app.use(cookieParser())
/*
app.use(
  session({
    secret: 'random key generated by monkeys', 
    resave: false, 
    saveUninitialized: false,
    store: new MongoStore({
      mongoUrl: process.env.MONGODB_URL
    }),
    cookie: { maxAge: 60 * 60 * 24 } //dure une journée
  }))*/
app.use(cors())
app.use(fileUpload({
  useTempFiles: true
}))
/*app.use(function(req, res, next) {
  res.locals.session = req.session;
})*/


// routes

app.use('/api/user', userRoutes);
app.use('/api/products', productRoutes);
app.use('/api/cart', cartRoutes);
app.use('/api/verif', verifRoutes);

module.exports = app